# Generated by Django 4.1.7 on 2023-03-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confection_name', models.CharField(max_length=64)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('confection_country', models.CharField(max_length=64)),
                ('confection_calories', models.IntegerField(default=0)),
                ('confection_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
