# Generated by Django 4.1.7 on 2023-03-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fridge_rat_confection_current_fridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confection',
            name='current_fridge',
        ),
    ]
