# Generated by Django 4.1.7 on 2023-03-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_confection_current_fridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='confection',
            name='current_fridge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.fridge'),
            preserve_default=False,
        ),
    ]
