# Generated by Django 4.1.7 on 2023-03-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_confection_current_fridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confection',
            name='current_fridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confections', to='api.fridge'),
        ),
        migrations.CreateModel(
            name='ClaimedCheeses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese_amount', models.IntegerField(default=0)),
                ('cheese_type', models.CharField(max_length=64)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheeses', to='api.fridge')),
                ('rat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheeses', to='api.rat')),
            ],
            options={
                'unique_together': {('fridge', 'rat')},
            },
        ),
        migrations.AddField(
            model_name='rat',
            name='fridges',
            field=models.ManyToManyField(blank=True, related_name='rats', through='api.ClaimedCheeses', to='api.fridge'),
        ),
    ]
