# Generated by Django 4.1.7 on 2023-03-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_confection_current_fridge_claimedcheeses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimedCheeses',
            new_name='ClaimedCheese',
        ),
    ]
